[kapitalbank-uz] new test
zenmoney/ZenPlugins pull request #528
Opened 2020-08-24 13:05 UTC by svvdg

2020-08-24 13:11 UTC, skvav commented on src/plugins/kapitalbank-uz/__tests__/transactions/outcome.test.js
> +        },
Вот тут лучше мерчанта не писать, потому как это не сам перевод, а комиссия по нему. Потому надо details в comment записать, а merchant: null сделать

2020-08-24 13:11 UTC, skvav commented on src/plugins/kapitalbank-uz/__tests__/transactions/outerOutcomeTransfer.test.js
> +  // convertWalletTransaction,
Лучше эти комментарии почистить

2020-08-24 13:36 UTC, svvdg commented
Исправил замечания

2020-08-25 05:39 UTC, kholmukhamedovme commented on src/plugins/kapitalbank-uz/api.js
> +import { InvalidPreferencesError } from '../../errors' // Ok 63, 94, 121
Что это за комментарии?

2020-08-25 05:41 UTC, kholmukhamedovme commented on src/plugins/kapitalbank-uz/converters.js
> +    syncID: [account.account],
Почему убираем? `account.id` встречается практически во всех операциях. Или то, что оно указано в `id` объекта уже по-умолчанию ставит его в `syncID`?

2020-08-25 05:51 UTC, kholmukhamedovme requested changes
В отправленных логах мною логах есть операции в JSON от банка и по картам UzCard и Visa, и по счету, и по кошельку. Можешь ориентироваться на них. Вечером попробую запустить плагин локально и проверить работу, боюсь могло что-то поломаться.

2020-08-25 05:51 UTC, kholmukhamedovme commented on src/plugins/kapitalbank-uz/converters.js
> +      city: rawTransaction.city,
Этих полей нет в ответе от банка. `rawTransaction` отличается от типа счета.

2020-08-25 06:49 UTC, skvav commented on src/plugins/kapitalbank-uz/api.js
> +import { InvalidPreferencesError } from '../../errors' // Ok 63, 94, 121
@svvdg да, тут надо тоже почистить комментарии. Комментарии вообще лучше оставлять только у себя, и в репозиторий не заливать. Лучше всего когда код понятен без комментариев и покрыт тестами.

2020-08-25 06:51 UTC, skvav commented on src/plugins/kapitalbank-uz/converters.js
> +    syncID: [account.account],
@kholmukhamedovme По задумке syncID - это массив неизменных идентификаторов, понятных пользователю. Т.е. это реальные номера счетов и карт, которые обрезаются автоматически до последних 4-ех символов. По ним происходит склейка счетов из плагина со счетами внутри приложения. А account.id - это строка для ссылок внутри операций на объект счета.

2020-08-25 10:12 UTC, svvdg commented on src/plugins/kapitalbank-uz/api.js
> +import { InvalidPreferencesError } from '../../errors' // Ok 63, 94, 121
Убрал лишнее

2020-08-25 10:13 UTC, svvdg commented on src/plugins/kapitalbank-uz/converters.js
> +      city: rawTransaction.city,
Поправил

2020-08-25 10:14 UTC, svvdg commented
Добавил тесты по Кошельку. Исправил замечания

2020-08-26 07:24 UTC, svvdg commented
Поправил api.js

2020-08-26 07:30 UTC, merged